### ISSUE TITLE
TS types not working

### ISSUE THREAD

**Issue by rlesniak** [pea-team/fower#18]
Simply not working 😄 

![image](https://user-images.githubusercontent.com/13970783/121694602-8b0cab80-caca-11eb-857b-9a6f95d7050d.png)

Versions
`"@fower/react-native": "^1.20.0",`
`"typescript": "~4.3.2"`

**Comment by forsigner** [comment]
@rlesniak fixed in new version: v1.21.0

**Comment by rlesniak** [comment]
Thanks. 

hmm, in your example in react native from docs still error 

![obraz](https://user-images.githubusercontent.com/13970783/121705691-315dae80-cad5-11eb-9f76-d90b964de5fc.png)

**Comment by forsigner** [comment]
Try to use in a new React Native project

**Comment by xdoer** [comment]
> Thanks.
> 
> hmm, in your example in react native from docs still error
> 
> ![obraz](https://user-images.githubusercontent.com/13970783/121705691-315dae80-cad5-11eb-9f76-d90b964de5fc.png)

fower does not support shadow prop, and the docs has error.
