### ISSUE TITLE
根据用户config动态生成类型定义

### ISSUE THREAD

**Issue by bingtsingw** [pea-team/fower#24]
目前的类型定义是在plugin包里写死的, 如果对config进行自定义, ts提示就和config不同步了.

是不是可以把生成types放在用户端, 可以根据不同的config生成不同的类型定义文件

**Comment by forsigner** [comment]
没太理解你意思，类型是可以通过 ts 类型合并实现自定义：

**Comment by bingtsingw** [comment]
合并类型只能增加, 不能减少, 如果color只定义了两个, 比如500和600, 还是会得到所有内置color的提示

**Comment by bingtsingw** [comment]
> 没理解 【是不是可以把生成types放在用户端, 可以根据不同的config生成不同的类型定义文件】这是什么意思

就是可以读取用户的config, 然后动态生成类型定义文件, 可以办到吗

**Comment by forsigner** [comment]
fower 暂时没配置文件，配置通过 `setConfig` 实现，暂时不想引进配置文件的概念，因为那需要约定文件名和路径

**Comment by bingtsingw** [comment]
我说的就是`setConfig`, 不知道是否可以在`setConfig`里面加个`generateTypes`的钩子

**Comment by forsigner** [comment]
这个也许可以，不过 `setConfig ` 是项目运行时，不是 build 运行时，可能不好搞

**Comment by bingtsingw** [comment]
我想到的是用一个单独的包来实现生成逻辑, `setConfig`里可以判断环境变量和包是否存在来开关生成的逻辑.
当然这个包可以不依赖`setConfig`, 比如cli执行读取某个config文件, 生成类型
