### ISSUE TITLE
expo 工程引入 报错

### ISSUE THREAD

**Issue by fantasyado** [pea-team/fower#25]
请问支持expo吗， 根据tutorial尝试显示ProfileCard 报错：

尝试显示的内容：
![image](https://user-images.githubusercontent.com/10321851/131819646-f5409d57-d8aa-49b9-b6f0-a58cc6940b76.png)

`TypeError: Object.entries requires that input parameter not be null or undefined

This error is located at:
    in StyledComponent (at FowerTest.js:7)
    in ProfileCard (at CustomerDetailScreen.js:213)
    in RCTView (at View.js:34)
    in View (at CustomerDetailScreen.js:147)
    in RCTScrollContentView (at ScrollView.js:1124)
    in RCTScrollView (at ScrollView.js:1260)
    in ScrollView (at ScrollView.js:1286)
    in ScrollView (at KeyboardAwareHOC.js:519)
    in KeyboardAwareScrollView (at CustomerDetailScreen.js:146)
    in RCTView (at View.js:34)
    in View (at CustomerDetailScreen.js:144)
    in CustomerDetailScreen (at SceneView.tsx:122)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:115)
    in EnsureSingleNavigator (at SceneView.tsx:114)
    in SceneView (at useDescriptors.tsx:153)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:245)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:244)
    in RCTView (at View.js:34)
    in View (at CardSheet.tsx:33)
    in ForwardRef(CardSheet) (at Card.tsx:573)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:555)
    in PanGestureHandler (at GestureHandlerNative.tsx:13)
    in PanGestureHandler (at Card.tsx:549)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:544)
    in RCTView (at View.js:34)
    in View (at Card.tsx:538)
    in Card (at CardContainer.tsx:206)
    in CardContainer (at CardStack.tsx:623)
    in RNSScreen (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at src/index.native.tsx:147)
    in Screen (at Screens.tsx:74)
    in MaybeScreen (at CardStack.tsx:616)
    in RNSScreenContainer (at src/index.native.tsx:186)
    in ScreenContainer (at Screens.tsx:50)
    in MaybeScreenContainer (at CardStack.tsx:498)
    in CardStack (at StackView.tsx:462)
    in KeyboardManager (at StackView.tsx:458)
    in SafeAreaProviderCompat (at StackView.tsx:455)
    in RCTView (at View.js:34)
    in View (at StackView.tsx:454)
    in StackView (at createStackNavigator.tsx:87)
    in StackNavigator (at AppNavigator.js:77)
    in MainFlow (at SceneView.tsx:122)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:115)
    in EnsureSingleNavigator (at SceneView.tsx:114)
    in SceneView (at useDescriptors.tsx:153)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:245)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:244)
    in RCTView (at View.js:34)
    in View (at CardSheet.tsx:33)
    in ForwardRef(CardSheet) (at Card.tsx:573)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:555)
    in PanGestureHandler (at GestureHandlerNative.tsx:13)
    in PanGestureHandler (at Card.tsx:549)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:544)
    in RCTView (at View.js:34)
    in View (at Card.tsx:538)
    in Card (at CardContainer.tsx:206)
    in CardContainer (at CardStack.tsx:623)
    in RNSScreen (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at src/index.native.tsx:147)
    in Screen (at Screens.tsx:74)
    in MaybeScreen (at CardStack.tsx:616)
    in RNSScreenContainer (at src/index.native.tsx:186)
    in ScreenContainer (at Screens.tsx:50)
    in MaybeScreenContainer (at CardStack.tsx:498)
    in CardStack (at StackView.tsx:462)
    in KeyboardManager (at StackView.tsx:458)
    in SafeAreaProviderCompat (at StackView.tsx:455)
    in RCTView (at View.js:34)
    in View (at StackView.tsx:454)
    in StackView (at createStackNavigator.tsx:87)
    in StackNavigator (at AppNavigator.js:124)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:409)
    in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:91)
    in ThemeProvider (at NavigationContainer.tsx:90)
    in ForwardRef(NavigationContainer) (at AppNavigator.js:116)
    in AppNavigator (at RootScreen.js:76)
    in RCTView (at View.js:34)
    in View (at RootScreen.js:74)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at src/index.tsx:85)
    in SafeAreaView (at RootScreen.js:70)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:76)
    in SafeAreaProvider (at RootScreen.js:69)
    in RCTView (at View.js:34)
    in View (at RootScreen.js:68)
    in ThemeProvider (at Provider.tsx:83)
    in RCTView (at View.js:34)
    in View (at PortalHost.tsx:125)
    in Portal.Host (at Provider.tsx:81)
    in Provider (at RootScreen.js:67)
    in RootScreen (at App.js:96)
    in Provider (at App.js:95)
    in App (created by ExpoRoot)
    in ExpoRoot (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in ChildrenWrapper (at wrapRootComponent.js:9)
    in _default (at wrapRootComponent.js:8)
    in Root (created by PatchedProviderComponent)
    in DevAppContainer (created by PatchedProviderComponent)
    in PatchedProviderComponent (at AppContainer.js:121)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
at node_modules/react-native/Libraries/Core/ReactFiberErrorDialog.js:43:2 in showErrorDialog
at [native code]:null in commitRootImpl
at [native code]:null in performSyncWorkOnRoot
at [native code]:null in dispatchAction
at node_modules/@react-navigation/core/src/useSyncState.tsx:39:22 in React.useCallback$argument_0
at node_modules/@react-navigation/core/src/SceneView.tsx:69:14 in React.useCallback$argument_0
at node_modules/@react-navigation/core/src/useOnAction.tsx:105:20 in React.useCallback$argument_0
at node_modules/@react-navigation/core/src/useNavigationHelpers.tsx:45:30 in dispatch
at node_modules/@react-navigation/core/src/BaseNavigationContainer.tsx:144:41 in listeners.focus._$argument_0
at node_modules/@react-navigation/core/src/useFocusedListenersChildrenAdapter.tsx:34:48 in React.useCallback$argument_0
at node_modules/@react-navigation/core/src/useFocusedListenersChildrenAdapter.tsx:27:46 in React.useCallback$argument_0
at node_modules/@react-navigation/core/src/BaseNavigationContainer.tsx:144:6 in dispatch
at src/navigation/RootNavigation.js:8:15 in AppNav.navigate
at src/screens/search/SearchScreen.js:116:20 in searchCustomer
at [native code]:null in flushedQueue
at [native code]:null in invokeCallbackAndReturnFlushedQueue`

**Comment by xdoer** [comment]
支持 expo, 文档中的 ProfileCard 示例有误，请查看最新文档，并更新一下 fower 版本。

**Comment by fantasyado** [comment]
> 支持 expo, 文档中的 ProfileCard 示例有误，请查看最新文档，并更新一下 fower 版本。

更新了下新版本可以了，不过文档里还是有问题，RN里面文字只能放在<Text></Text>里， 文档里是用View 包裹的   Steve Jobs，
不知道你说的最新文档是不是这个  https://fower.vercel.app/zh-cn/docs/use-with-rn

**Comment by xdoer** [comment]
你先看英文版的文档。中文文档较旧，有空我再完善一下中文文档

**Comment by fantasyado** [comment]
> 你先看英文版的文档。中文文档较旧，有空我再完善一下中文文档

OK,  Thanks
